/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lettersSidebar: [
    {
      type: 'category',
      label: 'Letters',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Partnership Letters',
          items: [
            {
              type: 'autogenerated',
              dirName: 'letters/partnership',
            },
          ],
        },
        {
          type: 'category',
          label: 'Berkshire Letters',
          items: [
            {
              type: 'autogenerated',
              dirName: 'letters/berkshire',
            },
          ],
        },
        {
          type: 'category',
          label: 'Special Letters',
          items: [
            {
              type: 'autogenerated',
              dirName: 'letters/special',
            },
          ],
        },
      ],
    },
  ],

  conceptsSidebar: [
    {
      type: 'doc',
      id: 'concepts/intro',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'concepts',
    },
  ],

  companiesSidebar: [
    {
      type: 'doc',
      id: 'companies/intro',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'companies',
    },
  ],

  peopleSidebar: [
    {
      type: 'doc',
      id: 'people/intro',
      label: 'Introduction',
    },
    {
      type: 'autogenerated',
      dirName: 'people',
    },
  ],
};

module.exports = sidebars;
